### PR TITLE
style: format, fix: minor fix in package.json, switched to yarn, feat: tests

### PR DESCRIPTION
**Pull request by GmBodhi**

### CODE REVIEW

**Comment by leonardobagi** [comment]
By the way at `index.d.ts`, the `execute()` method in `TmiCommand` does not return a Promise in any way as far as I know, that is not necessary and can be a issue when developing the commands in TypeScript

**Comment by GmBodhi** [comment]
> By the way at `index.d.ts`, the `execute()` method in `TmiCommand` does not return a Promise in any way as far as I know, that is not necessary and can be a issue when developing the commands in TypeScript

It'll help them to make the method async if they want. And that's unpredictable

**Comment by GmBodhi** [comment]
> > By the way at `index.d.ts`, the `execute()` method in `TmiCommand` does not return a Promise in any way as far as I know, that is not necessary and can be a issue when developing the commands in TypeScript
> 
> It'll help them to make the method async if they want. And that's unpredictable, it won't cause any problem unless it's returns something other than void

**Comment by EmanSza** [comment]
Due to the major changes by leonardo this pull request will be closed due to issues with all of the files. please make a new requested with version 1.3.0

**Comment by GmBodhi** [comment]
Sure, I'll do it once I'm back again!

**Comment by EmanSza** [comment]
Pull Request reopened. rebase still required

**Comment by leonardobagi** [comment]
This request is extremely outdated and needs a rebase for the merge

**Pull request closed without merging**
